### ISSUE TITLE
Missing material in walls on OSX

### ISSUE THREAD

**Issue by szemenyeim** [TimmHess/UERoboCup#1]
Hi, I've got an issue with missing assets when opening the training set generator with the unreal editor:

Error /Game/Scenes/PlayfieldSimulation_inProgress : Can't find file for asset. /Game/Materials/M_Basic_Wall
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by Model_5
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by ModelComponent_0
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by ModelComponent_1
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by ModelComponent_4
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by ModelComponent_5
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by Polys_84
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by Polys_102
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by Polys_147
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by Polys_195
Info Failed to load /Game/Materials/M_Basic_Wall.M_Basic_Wall Referenced by Polys_308

The images it generates have no wall textures but are otherwise OK.

I'm using MacOS X Sierra and Unreal Engine v4.16.3. I also have the substance plugin installed to the engine.

I noticed that there is a commit fixing missing materials, so I tried checking it (and the one before that) out, but I get the same error.

Thank you for sharing this great tool!

**Comment by TimmHess** [comment]
Hi, 
thank you for notifing me!
Something went wrong in my last fix and I did not notice.. sorry about that.
I pushed a new fix. Please let me know if you run in any other problems.

Kind regards,
Timm

**Comment by szemenyeim** [comment]
Hi,

thanks for the quick fix, it works perfectly now.

Kind regards,
Marton
